---
name: Build iperf3 for MiSTer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions: write-all

jobs:
  build_iperf3:
    runs-on: ubuntu-latest
    env:
      IPERF3_VERSION: "3.21"

    steps:
      - uses: actions/checkout@v4

      - name: Check version cache
        id: cache-check
        uses: actions/cache@v4
        with:
          path: /tmp/build-status.txt
          key: fastfetch-${{ env.IPERF3_VERSION }}

      - name: Install apt-get utilities
        if: steps.cache-check.outputs.cache-hit != 'true' ||
          github.event_name == 'pull_request'

        run: >
          sudo apt update &&
          sudo apt-get install -y -qq autoconf binfmt-support build-essential gcc make qemu-user-static gcc-arm-linux-gnueabihf
            # sharutils
            # u-boot-tools
            # curl
            # git
            # qemu-user

      - name: Build iperf3
        if: steps.cache-check.outputs.cache-hit != 'true'  ||
          github.event_name == 'pull_request'
        env:
          GCC_VERSION: 10.2-2020.11
        run: |
          .github/build_iperf3.sh

      - name: Update cache version
        if: steps.cache-check.outputs.cache-hit != 'true' &&
          github.ref == 'refs/heads/main'
        run: >
          echo "${{ env.IPERF3_VERSION }}" > /tmp/build-status.txt


      - name: Commit and push changes
        if: steps.cache-check.outputs.cache-hit != 'true'
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Updated Scripts directory

      - name: Build Custom Database for MiSTer Downloader
        if: github.ref == 'refs/heads/main'
        run: >
          sudo chown -R runner .git ;
          set -o pipefail
          && curl --fail --location https://raw.githubusercontent.com/theypsilon/Downloader_DB-Template_MiSTer/main/.github/build_db.py
          | python3 -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
